name: ABS-KoSync Enhanced-2
version: 1.2.1
slug: abs-kosync-enhanced-2
description: (Enhanced with Web-UI and three-way sync)The missing link between your ears and your eyes. Seamlessly sync your reading progress between Audiobookshelf (Audiobooks) and KOReader/KoSync (Ebooks). Start listening in the car, and pick up exactly where you left off on your Kindle or Kobo. (Enhanced with three-way sync)
arch:
  - amd64
  - aarch64
boot: manual
options:
  LOG_LEVEL: INFO
  TZ: America/Los_Angeles
  KOSYNC_PORT: 5758
schema:
  LOG_LEVEL: str
  TZ: str
  KOSYNC_PORT: int
ports:
  5757/tcp: 5759
  5758/tcp: 5760
ports_description:
  5757/tcp: Admin Panel (Keep Private)
  5758/tcp: Sync Protocol (Safe to Expose)
webui: http://[HOST]:[PORT:5759]
legacy: true
map:
  - media:rw
  - addon_config:rw
  - backup:rw
  - share:rw
